### ISSUE TITLE
The pin is not anchored at the correct spot

### ISSUE THREAD

**Issue by gadzair** [javiholcman/Wapps.Forms.Map#1]
When you rotate the screen the pin bottom moves around a lot. It needs to be anchored at the middle of the bottom.

**Comment by javiholcman** [comment]
Is this happening on iOS or Android?

**Comment by gadzair** [comment]
iOS; I fixed it actually. I do the following in GetViewForAnnotation:
annotationView.CenterOffset = new CGPoint((formsView.WidthRequest / 2) - formsView.AnchorX, (formsView.HeightRequest / 2) - formsView.AnchorY);

And then in the xaml I can use AnchorX and AnchorY to set the anchor point of the pin. Do you prefer I create a pull request?

**Comment by gadzair** [comment]
Ok that code was slightly bad; Anchor properties in Xamarin are supposed to be from 0 to 1. Anyhow I created the pull request #3 to solve this issue along with updating the demo and both Android and iOS to honor it. Hope you accept it @javiholcman .
